version: '2'

services:
  db-userauth:
    image: "mysql/mysql-server:8.0"
    container_name: db-userauth
    command: [ "mysqld",
                "--character-set-server=utf8mb4",
                "--collation-server=utf8mb4_unicode_ci",
                "--bind-address=0.0.0.0",
                "--socket=/tmp/mysql.sock" ]
    expose:
      - "3306"
    networks:
      - authnet
    volumes:
      - db-userauth-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "testtest"
      MYSQL_USER: userauth
      MYSQL_PASSWORD: userauth
      MYSQL_DATABASE: userauth

  svc-userauth:
    build: ../notey-users
    container_name: svc-userauth
    depends_on:
      - db-userauth
    networks:
      - authnet
      - svcnet
    # DO NOT EXPOSE THIS PORT ON PRODUCTION
    ports:
      - "5858:5858"
    restart: always

  db-notes:
    image: "mysql/mysql-server:8.0"
    container_name: db-notes
    command: [ "mysqld",
                "--character-set-server=utf8mb4",
                "--collation-server=utf8mb4_unicode_ci",
                "--bind-address=0.0.0.0",
                "--socket=/tmp/mysql.sock" ]
    expose:
      - "3306"
    networks:
      - frontnet
    volumes:
      - db-notes-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "testtest"
      MYSQL_USER: notes
      MYSQL_PASSWORD: notes
      MYSQL_DATABASE: notes

  svc-notes:
    build: ../notey-notes
    container_name: svc-notes
    depends_on:
      - db-notes
    networks:
      - frontnet
      - svcnet
    ports:
      - "3000:3000"
    restart: always

networks:
  frontnet:
    driver: bridge
  authnet:
    driver: bridge
  svcnet:
    driver: bridge

volumes:
  db-userauth-data:
  db-notes-data: